name: Minha Primeira Linha de Montagem

on:
  push:
    branches: [ main ]

jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    steps:
      - name: 1. checkout do código
        uses: actions/checkout@v4

      - name: 2. executar teste e gerar identificador
        run: echo "Construindo o projeto... Verificando se todas as peças se encaixam!"

      - name: 3. disponibilizar artefato
        run: echo "eu yasmin concluiu o teste de versionamento na data de$(25/06)"

      
